export const medicationData = [
  {
    medicationName: "Paracetamol",
    dose: "500mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 6 giờ khi cần.",
    price: 2000,
  },
  {
    medicationName: "Ibuprofen",
    dose: "200mg",
    quantity: 30,
    instructions: "Uống 1-2 viên mỗi 8 giờ.",
    price: 3000,
  },
  {
    medicationName: "Amoxicillin",
    dose: "500mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 12 giờ trong 7 ngày.",
    price: 5000,
  },
  {
    medicationName: "Loratadine",
    dose: "10mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 4000,
  },
  {
    medicationName: "Metformin",
    dose: "500mg",
    quantity: 60,
    instructions: "Uống 1 viên mỗi bữa ăn.",
    price: 1500,
  },
  {
    medicationName: "Simvastatin",
    dose: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 7000,
  },
  {
    medicationName: "Omeprazole",
    dose: "20mg",
    quantity: 28,
    instructions: "Uống 1 viên mỗi sáng trước khi ăn.",
    price: 6000,
  },
  {
    medicationName: "Aspirin",
    dose: "81mg",
    quantity: 100,
    instructions: "Uống 1 viên mỗi ngày sau bữa ăn.",
    price: 1000,
  },
  {
    medicationName: "Cetrizine",
    dose: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Clopidogrel",
    dose: "75mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 6000,
  },
  {
    medicationName: "Levothyroxine",
    dose: "50mcg",
    quantity: 30,
    instructions: "Uống 1 viên vào buổi sáng khi bụng đói.",
    price: 2500,
  },
  {
    medicationName: "Furosemide",
    dose: "40mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 2000,
  },
  {
    medicationName: "Doxycycline",
    dose: "100mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 4500,
  },
  {
    medicationName: "Azithromycin",
    dose: "250mg",
    quantity: 6,
    instructions: "Uống 2 viên ngày đầu, sau đó 1 viên mỗi ngày.",
    price: 12000,
  },
  {
    medicationName: "Prednisone",
    dose: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày hoặc theo chỉ định.",
    price: 3000,
  },
  {
    medicationName: "Hydrochlorothiazide",
    dose: "25mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi sáng.",
    price: 2000,
  },
  {
    medicationName: "Warfarin",
    dose: "5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Alprazolam",
    dose: "0.5mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 8 giờ khi cần.",
    price: 8000,
  },
  {
    medicationName: "Ciprofloxacin",
    dose: "500mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 7000,
  },
  {
    medicationName: "Metronidazole",
    dose: "500mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 8 giờ.",
    price: 4000,
  },
  {
    medicationName: "Lisinopril",
    dose: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Gabapentin",
    dose: "300mg",
    quantity: 90,
    instructions: "Uống 1 viên mỗi 8 giờ.",
    price: 10000,
  },
  {
    medicationName: "Meloxicam",
    dose: "15mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 3500,
  },
  {
    medicationName: "Allopurinol",
    dose: "300mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 4500,
  },
  {
    medicationName: "Atorvastatin",
    dose: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi tối.",
    price: 7000,
  },
  {
    medicationName: "Esomeprazole",
    dose: "40mg",
    quantity: 28,
    instructions: "Uống 1 viên mỗi ngày trước khi ăn.",
    price: 9500,
  },
  {
    medicationName: "Tamsulosin",
    dose: "0.4mg",
    quantity: 30,
    instructions: "Uống 1 viên sau bữa ăn tối.",
    price: 6000,
  },
  {
    medicationName: "Amlodipine",
    dose: "5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Venlafaxine",
    dose: "75mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 8500,
  },
  {
    medicationName: "Clonazepam",
    dose: "0.5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 7500,
  },
  {
    medicationName: "Sertraline",
    dose: "50mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 8000,
  },
  {
    medicationName: "Zolpidem",
    dose: "10mg",
    quantity: 10,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 12000,
  },
  {
    medicationName: "Tramadol",
    dose: "50mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 6 giờ khi cần.",
    price: 4000,
  },
  {
    medicationName: "Fluoxetine",
    dose: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 7500,
  },
  {
    medicationName: "Bupropion",
    dose: "150mg",
    quantity: 60,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 15000,
  },
  {
    medicationName: "Ranitidine",
    dose: "150mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 3500,
  },
  {
    medicationName: "Montelukast",
    dose: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày vào buổi tối.",
    price: 8500,
  },
  {
    medicationName: "Duloxetine",
    dose: "60mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 9500,
  },
  {
    medicationName: "Mirtazapine",
    dose: "15mg",
    quantity: 30,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 7000,
  },
  {
    medicationName: "Famotidine",
    dose: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày trước khi ăn.",
    price: 5000,
  },
];
