export const medicationData = [
  {
    medicationName: "Paracetamol",
    dosage: "500mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 6 giờ khi cần.",
    price: 2000,
  },
  {
    medicationName: "Ibuprofen",
    dosage: "200mg",
    quantity: 30,
    instructions: "Uống 1-2 viên mỗi 8 giờ.",
    price: 3000,
  },
  {
    medicationName: "Amoxicillin",
    dosage: "500mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 12 giờ trong 7 ngày.",
    price: 5000,
  },
  {
    medicationName: "Loratadine",
    dosage: "10mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 4000,
  },
  {
    medicationName: "Metformin",
    dosage: "500mg",
    quantity: 60,
    instructions: "Uống 1 viên mỗi bữa ăn.",
    price: 1500,
  },
  {
    medicationName: "Simvastatin",
    dosage: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 7000,
  },
  {
    medicationName: "Omeprazole",
    dosage: "20mg",
    quantity: 28,
    instructions: "Uống 1 viên mỗi sáng trước khi ăn.",
    price: 6000,
  },
  {
    medicationName: "Aspirin",
    dosage: "81mg",
    quantity: 100,
    instructions: "Uống 1 viên mỗi ngày sau bữa ăn.",
    price: 1000,
  },
  {
    medicationName: "Cetrizine",
    dosage: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Clopidogrel",
    dosage: "75mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 6000,
  },
  {
    medicationName: "Levothyroxine",
    dosage: "50mcg",
    quantity: 30,
    instructions: "Uống 1 viên vào buổi sáng khi bụng đói.",
    price: 2500,
  },
  {
    medicationName: "Furosemide",
    dosage: "40mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 2000,
  },
  {
    medicationName: "Doxycycline",
    dosage: "100mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 4500,
  },
  {
    medicationName: "Azithromycin",
    dosage: "250mg",
    quantity: 6,
    instructions: "Uống 2 viên ngày đầu, sau đó 1 viên mỗi ngày.",
    price: 12000,
  },
  {
    medicationName: "Prednisone",
    dosage: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày hoặc theo chỉ định.",
    price: 3000,
  },
  {
    medicationName: "Hydrochlorothiazide",
    dosage: "25mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi sáng.",
    price: 2000,
  },
  {
    medicationName: "Warfarin",
    dosage: "5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Alprazolam",
    dosage: "0.5mg",
    quantity: 14,
    instructions: "Uống 1 viên mỗi 8 giờ khi cần.",
    price: 8000,
  },
  {
    medicationName: "Ciprofloxacin",
    dosage: "500mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 7000,
  },
  {
    medicationName: "Metronidazole",
    dosage: "500mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 8 giờ.",
    price: 4000,
  },
  {
    medicationName: "Lisinopril",
    dosage: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Gabapentin",
    dosage: "300mg",
    quantity: 90,
    instructions: "Uống 1 viên mỗi 8 giờ.",
    price: 10000,
  },
  {
    medicationName: "Meloxicam",
    dosage: "15mg",
    quantity: 10,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 3500,
  },
  {
    medicationName: "Allopurinol",
    dosage: "300mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 4500,
  },
  {
    medicationName: "Atorvastatin",
    dosage: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi tối.",
    price: 7000,
  },
  {
    medicationName: "Esomeprazole",
    dosage: "40mg",
    quantity: 28,
    instructions: "Uống 1 viên mỗi ngày trước khi ăn.",
    price: 9500,
  },
  {
    medicationName: "Tamsulosin",
    dosage: "0.4mg",
    quantity: 30,
    instructions: "Uống 1 viên sau bữa ăn tối.",
    price: 6000,
  },
  {
    medicationName: "Amlodipine",
    dosage: "5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 5000,
  },
  {
    medicationName: "Venlafaxine",
    dosage: "75mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 8500,
  },
  {
    medicationName: "Clonazepam",
    dosage: "0.5mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 7500,
  },
  {
    medicationName: "Sertraline",
    dosage: "50mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 8000,
  },
  {
    medicationName: "Zolpidem",
    dosage: "10mg",
    quantity: 10,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 12000,
  },
  {
    medicationName: "Tramadol",
    dosage: "50mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi 6 giờ khi cần.",
    price: 4000,
  },
  {
    medicationName: "Fluoxetine",
    dosage: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 7500,
  },
  {
    medicationName: "Bupropion",
    dosage: "150mg",
    quantity: 60,
    instructions: "Uống 1 viên mỗi 12 giờ.",
    price: 15000,
  },
  {
    medicationName: "Ranitidine",
    dosage: "150mg",
    quantity: 20,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 3500,
  },
  {
    medicationName: "Montelukast",
    dosage: "10mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày vào buổi tối.",
    price: 8500,
  },
  {
    medicationName: "Duloxetine",
    dosage: "60mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày.",
    price: 9500,
  },
  {
    medicationName: "Mirtazapine",
    dosage: "15mg",
    quantity: 30,
    instructions: "Uống 1 viên trước khi đi ngủ.",
    price: 7000,
  },
  {
    medicationName: "Famotidine",
    dosage: "20mg",
    quantity: 30,
    instructions: "Uống 1 viên mỗi ngày trước khi ăn.",
    price: 5000,
  },
];

export const processSteps = [
  {
    title: "LÊN LỊCH HẸN KHÁM",
    details: [
      "Đăng ký sử dụng hệ thống đặt lịch hẹn trực tuyến.",
      "Chọn hình thức khám: Theo ngày hoặc theo khung giờ.",
      "Nhập thông tin bệnh nhân: Số hồ sơ bệnh án hoặc bệnh nhân mới.",
      "Chọn thông tin khám: Chuyên khoa, bác sĩ, ngày khám, giờ khám (nếu có).",
    ],
  },
  {
    title: "THANH TOÁN PHÍ KHÁM",
    details: [
      "Chọn phương thức thanh toán: Thẻ bệnh viện, căn cước công dân, hoặc thẻ ATM, v.v.",
      "Kiểm tra số tiền cần thanh toán, chọn phương thức thanh toán.",
      "Nhập thông tin để hoàn tất thanh toán.",
    ],
  },
  {
    title: "XÁC NHẬN BỆNH NHÂN ĐẾN BỆNH VIỆN",
    details: [
      "Sau khi thanh toán thành công, xác nhận sẽ được gửi qua email, tin nhắn hoặc trên trang web.",
      "Vào ngày khám:",
      "Bệnh nhân không có hồ sơ bệnh án đến quầy tiếp nhận trước giờ hẹn 15-30 phút.",
      "Bệnh nhân có hồ sơ bệnh án đến trước giờ hẹn 15-30 phút để xác nhận thông tin trước khi vào phòng khám.",
    ],
  },
  {
    title: "KHÁM VÀ XÉT NGHIỆM",
    details: [
      "Bệnh nhân được khám tại phòng khám chuyên khoa theo lịch hẹn.",
      "Thực hiện các xét nghiệm và chẩn đoán hình ảnh (nếu có) theo chỉ định của bác sĩ.",
      "Sau khi nhận kết quả xét nghiệm, bệnh nhân quay lại phòng khám để bác sĩ đánh giá và kê đơn điều trị.",
    ],
  },
  {
    title: "NHẬN THUỐC",
    details: [
      "Bệnh nhân có bảo hiểm y tế: Nhận thuốc tại quầy 17, 18, 19, 20 sau khi thanh toán phần chênh lệch (nếu có).",
      "Bệnh nhân không có bảo hiểm y tế: Nhận thuốc tại quầy A hoặc B sau khi thanh toán tại quầy thu ngân hoặc chuyển khoản vào tài khoản thanh toán khám (nếu có).",
    ],
  },
  {
    title: "LÊN LỊCH TÁI KHÁM",
    details: [
      "Sử dụng hệ thống đặt lịch hẹn như ở BƯỚC 1 và BƯỚC 2 để nhận phiếu hẹn điện tử.",
    ],
  },
];

export const reqTestData = [
  {
    _id: "YCXN-033564",
    test: [
      {
        _id: "1",
        testName: "Xét nghiệm viêm gan B",
        price: 300000,
        description: "",
      },
      {
        _id: "2",
        testName: "Xét nghiệm chức năng thận",
        price: 140000,
        description: "",
      },
    ],
    patientId: "BN-5C662W",
    doctorId: "BS-98ANP7",
    reason: "Xin lỗi anh chịu hông nổi, xin lỗi vì quá đẹp trai",
    requestDate: new Date(),
  },
  {
    _id: "YCXN-033546",
    test: [
      {
        _id: "3",
        testName: "Xét nghiệm dị ứng",
        price: 200000,
        description: "",
      },
      {
        _id: "4",
        testName: "Xét nghiệm ung thư",
        price: 200000,
        description: "",
      },
    ],
    patientId: "BN-PMQ7TS",
    doctorId: "BS-98ANP7",
    reason:
      "Nhận ra mình ở quận ba đình, quay đầu thấy mấy thèn em ở trên cầu giấy",
    requestDate: new Date(),
  },
];

export const apmtData = [
  {
    patientId: "BN-5C662W",
    appointmentDate: "2024-11-17T02:00:00.000Z",
    reason: "Kiểm tra định kỳ",
    status: "Scheduled",
    specialization: "Cardiology",
    priority: false,
    createdAt: "2024-11-13T11:33:01.086Z",
    updatedAt: "2024-11-13T11:33:01.086Z",
    _id: "CH-K4E64V",
    __v: 0,
  },
  {
    patientId: "BN-ZRVR3W",
    appointmentDate: "2024-11-19T02:00:00.000Z",
    reason: "Kiểm tra trả kim?",
    status: "Scheduled",
    specialization: "Cardiology",
    priority: false,
    _id: "CH-K4E64V",
  },
  {
    patientId: "BN-7UHDY1",
    appointmentDate: "2024-11-19T02:00:00.000Z",
    reason: "Thuỷ tổ Gò Vấp",
    status: "Scheduled",
    specialization: "Cardiology",
    priority: false,
    _id: "CH-K4E64V",
  },
];
