import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { viVN } from "@clerk/localizations";
import ClientWrapper from "./ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laman Clinic",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={viVN}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Suspense fallback={<div>Loading...</div>}>
            <NextTopLoader />
            <ClientWrapper>{children}</ClientWrapper>
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
